---
title: "Discussion"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Leave a comment here

```{r eval=FALSE, echo=FALSE}
# You can inject raw HTML, including script tags, directly into your R Markdown document. However, to ensure that R Markdown processes this correctly when rendering to HTML, you can wrap the script in a custom HTML block using R code. This method involves using the htmltools package, which is part of the R ecosystem for creating and manipulating HTML content.

htmltools::tags$script(src="https://utteranc.es/client.js",
                       repo="jialianghua/mentalhealthdatascience",
                       `issue-term`="pathname",
                       label="Comment",
                       theme="github-light",
                       crossorigin="anonymous",
                       async="async")

# original script generated by https://utteranc.es; uncomment to show it.
# <script src="https://utteranc.es/client.js"
#         repo="jialianghua/mentalhealthdatascience"
#         issue-term="pathname"
#         label="Comment"
#         theme="github-light"
#         crossorigin="anonymous"
#         async>
# </script>
```

```{r echo=FALSE}
htmltools::tags$script(src="https://giscus.app/client.js",
                       `data-repo`="jialianghua/mentalhealthdatascience",
                       `data-repo-id`="R_kgDOLfbK4g",
                       `data-category`="Announcements",
                       `data-category-id`="DIC_kwDOLfbK4s4Cd8_M",
                       `data-mapping`="pathname",
                       `data-strict`="0",
                       `data-reactions-enabled`="1",
                       `data-emit-metadata`="0",
                       `data-input-position`="top",
                       `data-theme`="light",
                       `data-lang`="en",
                       crossorigin="anonymous",
                       async="async")
```

Here's back to the [index](index.html) page.